require("config.options")
require("config.keymaps")
require("config.autocmds")
require("plugins.treesitter")
require("custom.statusline")
require("custom.autopairs")
require("plugins.fzf")
require("plugins.cmp")
require("plugins.lsp")

vim.cmd.colorscheme("kanagawa")
